# Generated by Django 5.0.1 on 2024-02-14 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointmentapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='Tblconsultations',
        ),
        migrations.DeleteModel(
            name='Tbldatacodemaster',
        ),
        migrations.DeleteModel(
            name='Tbldoctorappointments',
        ),
        migrations.DeleteModel(
            name='Tbldoctorlocationavailability',
        ),
        migrations.DeleteModel(
            name='Tbldoctorlocations',
        ),
        migrations.DeleteModel(
            name='TbldoctorMedicines',
        ),
        migrations.DeleteModel(
            name='Tbldoctors',
        ),
        migrations.DeleteModel(
            name='TblmedicineInstructions',
        ),
        migrations.DeleteModel(
            name='TblpateintCharges',
        ),
        migrations.DeleteModel(
            name='Tblpatientbiometrics',
        ),
        migrations.DeleteModel(
            name='TblpatientComplaints',
        ),
        migrations.DeleteModel(
            name='TblpatientFindingsandsymtoms',
        ),
        migrations.DeleteModel(
            name='TblpatientLabinvestigations',
        ),
        migrations.DeleteModel(
            name='TblpatientMedications',
        ),
        migrations.DeleteModel(
            name='TblpatientPayments',
        ),
        migrations.DeleteModel(
            name='Tblpatients',
        ),
        migrations.DeleteModel(
            name='Tblpatientvitals',
        ),
        migrations.DeleteModel(
            name='Tblprescriptions',
        ),
    ]
